os: linux
dist: xenial
language: python
python: "3.7"

script:
  - pip install requests requests[security] 
  - echo "-------------------------INSIDE PYTHON------------------------------------"
  - python run.py



