os: linux
dist: xenial
language: python
python: "3.7"

script:
  - pip install requests==2.21
  - echo "-------------------------INSIDE PYTHON------------------------------------"
  - python run2.py
 



